### ISSUE TITLE
[TODO] Move in page JS to an external js sheet.

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#105]
I want to move the majority of the java-script to a minified js file. The idea is that each page will have core javascript in the page only as well as a document load and a timers function for polling. Everything else should be moved so I can cut down on clutter.

## footer.njk - globals
-  [ ]  [showInfo](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/partials/footer.njk#L115-L121) 
-  [ ]  [setWaypoint](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/partials/footer.njk#L123-L129)
- [ ] [tooltips](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/partials/footer.njk#L41-L44)
- [ ] [birdAlert notifications](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/partials/footer.njk#L29-L37)
- [ ] [the entire notification system](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/partials/footer.njk#L57-L113) -- This quite frankly needs an overhaul to clean it up and reduce redundant code.

## fcFleetManagement.njk
- [ ] [invitePilot](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L303-L319)
- [ ] [removePilot](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L321-L341)
- [ ] [alarmUser](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L364-L383) -- The row colours are a bit buggy on this. If the user is alarmed twice on a page refresh the rows don't change correctly.
- [ ] [fleetComp](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L349-L362)
- [ ] [setFC](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L385-L395) -- the error to console indicates there was an issue setting the backseat this needs to state the error was updating the fc
- [ ] [setBackseat](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L397-L407)
- [ ] [updateComms](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L409-L419)
- [ ] [updateStatus](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L421-L432)
- [ ] [updateType](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L434-L445)
- [ ] [clearWaitlist](https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/fcFleetManage.njk#L447-L465) -- This may be causing an issue with the legals modal on the GET/commander/:fleetid view.

**Comment by samuelgrant** [comment]
The bottom of each view should only have this where possible plus any very specific one page javascript snippets.

`<script>
    //On page load
    $( document ).ready(function() {
       //put any view specific functions here that need to be called once after page load
    });

    //Start Timer
    setInterval(function()
    { 
      //put any view specific functions here that need to be called on a timer 
    }, 15000);//Every 15 seconds
</script>`

**Comment by samuelgrant** [comment]
Any part of the script that requires variables needs to be within the view file in the footer.
