### ISSUE TITLE
[TODO] Pilot Skills

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#120]
The whole skills check function is yucky. The code needs to be reworked.
- [] Move skills out of users.js
- [] Do we want a pilot skills object so we can check them if they revoke the token yes/no?
- [] Fix the bug where the view errors if no skills can be read (esi failure / pilot revoked token)
