### ISSUE TITLE
Quick TODO: Remove pilot from fleet button

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#133]
There is a red button that gets added to this table via ajax. This button should remove a pilot from the fleet. More might be added later such as player stats but we can look at that in a later time. 

For now:
- [ ] Remove disabled class from the button. 
- [ ] OnClick turn row blue and call function to remove them from fleet
- [ ] On success turn red. Will be removed by ajax on page refresh

https://github.com/Makeshift/eve-goons-waitlist/blob/bad9413041e64afab42b1a2e06de53154691ac64/resources/views/fcFleetManage.njk#L190-L213
